---
title: "Treatment heterogeneity in comparative effectiveness of teriparatide vs bisphosphonates: multi-database cohort study"
output:
    bookdown::pdf_document2: default
    bookdown::word_document2:
        reference_docx: reference.docx
geometry: margin=1.0in
toc: false
font-size: 11pt
header-includes:
  - \renewcommand*\familydefault{\sfdefault}
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage[left]{lineno}
editor_options: 
  chunk_output_type: console
bibliography: references.bib
csl: jamia.csl
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

d <- function(x, decimals = 2) {
  sprintf(paste0("%1.", decimals, "f"), x) 
}

knit_hooks$set(
  inline = function(x) {
    prettyNum(
      x,
      big.mark = ",",
      decimal.mark = ".",
      preserve.width = "individual"
    )
  }
)
```

\vspace{35mm}



Alexandros Rekkas${^1}$, Annika M. J&ouml;dicke${^2}$, David van Klaveren$^3$,
Daniel Prieto-Alhambra${^{1,2}}$, Peter R. Rijnbeek${^1}$

\vspace{40mm}

$^1$ Department of Medical Informatics, Erasmus University Medical Center,
Rotterdam, Netherlands

$^2$ Pharmaco- and Device Epidemiology, Centre for Statistics in Medicine,
Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences,
University of Oxford, Oxford, UK

$^3$ Department of Public Health, Erasmus University Medical Center, Rotterdam,
Netherlands

\newpage

\linenumbers
# Introduction
Osteoporosis is a common condition characterised by decreased bone density and
associated with increased risk for fragility fractures, which affects almost
30% of women aged $\geq50$ years [@wright2017impact]. It was estimated that in
2005, over 2 million incident fractures occurred in the United States, with hip
fractures accounting for more than 70% of the costs. By 2025, annual fractures
and costs could rise by almost 50% [@Cole2008].

Fracture prevention is thus the key focus of anti-osteoporotic therapy,
reducing the disease burden both for the affected patient but also on the
population level. Several pharmacological agents are available for primary and
secondary prevention. The choice of anti-osteoporotic agent largely depends on
history of fragility fracture and anticipated fracture risk. Oral
bisphosphonates (BP) are first line treatments for postmenopausal patients with
increased fracture risk in clinical guidelines (#AACE/ACE 2020) as for their
favourable cost-effectiveness and safety profile. Teriparatide, a parathyroid
hormone analogue administered as a daily injection, was approved by the FDA in
2002 as the first anabolic agent for treatment of severe postmenopausal
osteoporosis. While clinical trials among patients with previous vertebral
fractures showed a substantial risk reduction for new vertebral fracture
comparing teriparatide to placebo [@Neer2001] and risedronate [@Kendler2018],
its efficacy on low-incident major osteoporotic fractures, especially hip
fractures, is less well established: Previous randomised trials assessing hip
fracture comprised only few events, thus not providing sufficient power to show
differences between treatment groups when studying comparative effectiveness. A
recent meta-analysis by Diez-Perez and colleagues assessed the effect of
teriparatide on hip fracture, indicating a significant 80% risk reduction
compared to placebo and a non-significant 46% risk reduction when compared to
active controls [@DezPrez2019].  

With teriparatide-containing biosimilars being launched in recent years,
treatment costs dropped significantly. Subsequently, the discussion of
cost-effectiveness in patients with less severe forms of osteoporosis is
restarting. Therefore, evaluation of the effectiveness in hip fracture
prevention is required. In particular, observational studies assessing
comparative effectiveness in a real-world setting are required, as
effectiveness may differ from clinical trial as for differences in patient’s
persistence and adherence to their anti-osteoporotic treatment. While hip
fracture is a comparatively rare outcome, it is unambiguously defined and
reliably recorded in routinely collected data, allowing for a direct comparison
to results from clinical trial meta-analyses. While results from
non-controlled, observational studies suggest that teriparatide may reduce the
risk of hip fractures [@Burge2016; @Silverman2018], this is the first
observational study assessing teriparatide in hip fracture risk reduction
compared to oral bisphosphonate users in postmenopausal women using multiple
large real-world databases.

\newpage
# Methods
## Study design

We performed a retrospective new user cohort study to estimate the effectiveness
of teriparatide compared to oral bisphosphonates in patients with
osteoporosis [@Ryan2013]. We included female participants above the age of 50
with established osteoporosis (any condition occurrence of hip, wrist, spine or
shoulder/humerus fracture in their history, prior to treatment initiation) and
at least 365 days of continuous observation period before the index event.
Patients were considered to be new-users if they received no anti-osteoporosis
drugs (raloxifene, bazedoxifene, denosumab, abaloparatide, romosozumab) 365 days
prior to treatment initiation with teriparatide or an oral bisphosphonate.

As a secondary analysis, we evaluated treatment effect heterogeneity using a risk-based approach. The 

Our primary efficacy outcome was hip fracture. Vertebral fracture and a
composite major osteoporotic fracture, defined as hip, vertebral or
wrist/forearm/proximal humerus fracture, were our secondary efficacy outcomes.
We excluded patients that had experienced the outcome under study any time
prior to treatment initiation. Patient time-at-risk started 1 day after
treatment initiation and finished 730 days after treatment initiation.

## Data sources

We ran our analyses on three US observational databases mapped to OMOP-CDM
version. More specifically:

- **IBM MarketScan Medicare Supplemental Database (MDCR)** is a claims database
  representing retirees in the United States with primary or Medicare
supplemental coverage.
- **Optum De-Identified Clinformatics® Data Mart Database – Date of Death
  (Optum-DOD)** is a claims database including members of private health
insurance.
- **Optum de-identified Electronic Health Record Dataset (Optum-EHR)** is an
  EHR database including Humedica’s Electronic Health Record.

##     Statistical analyses
We carried out two sets of analyses. First, we derived overall treatment effect
estimates of teriparatide compared to oral bisphosphonates regarding the three
outcomes of interest. To account for potential measured confounding we
developed separate large-scale propensity score models within each database
based on LASSO logistic regression using the same predefined set of measured
covariates [@Tian2018]. We estimated treatment effects using Cox proportional
hazards models with treatment as the sole covariate fitted in the 1:4
propensity score-matched subset of the considered patient population. Results
from different databases were summarized using random effects meta-analysis.

For the second set of analyses, we used the standardized framework for
risk-based assessment of treatment effect heterogeneity, that follows the
directives of the PATH statement [@Kent2019; @KentEnE2019]. Following data
extraction, the framework was applied in two steps. First, we derived
individualized risk predictions for the three efficacy outcomes. We built the
prediction models using LASSO logistic regression on the propensity score
matched (1:4) subpopulation of the pooled treatment arms, aiming to remove any
effect of measured confounding that may cause differential fit of our models
across treatment arms. We considered the same large set of candidate covariates
as for the development of the propensity score models.

For each outcome we used the derived prediction models to divide the population
in 4 equally-sized subgroups, based on the quarters of the predicted risk
distribution. Within each of these risk-based subgroups we developed a new
propensity score model. Our analyses were performed on the propensity score
matched (1:4) subset of the risk subgroup subset. We derived relative effect
estimates using Cox proportional hazards models only with treatment as a
predictor. Absolute effect estimates were calculated based on the difference of
the Kaplan-Meier estimates, on day 730 after treatment initiation.

Residual study bias from unmeasured confounding can still be present in
observational studies, which often may not be visible when evaluating
propensity score adjustment. To account for that, we considered a set of 126
negative control outcome experiments, where a null effect was assumed to be
true. We used the estimated relative effects for these outcomes to derive an
empirical approximation to the true null distribution, which was then used to
calibrate the hazard ratios and their 95% confidence intervals for the 3
outcomes of interest [@Schuemie2013; @Schuemie2016].

\newpage
# Results



\newpage
# Discussion

\newpage
# References
\setlength{\parindent}{-0.25in}
\setlength{\leftskip}{0.25in}
\noindent
<div id="refs"></div>
\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\noindent


\newpage
# Tables and figures

